[workspace]
members = [
    "ecdna",
    "ecdna-data",
    "ecdna-dynamics",
    "ecdna-sim",
]

[profile.release]
lto = "thin"
codegen-units = 1

[workspace.metadata]
name = "ecdna"
version = "0.4.4"

[workspace.dependencies]
anyhow = "1.0"
enum_dispatch = "0.3.7"
serde = { version = "1.0.136", features = ["derive"] }
rand = { version = "0.8.0", features = ["small_rng"] }
rand_pcg = "0.3.1"
rand_distr = "0.4.0"
fake = "2.4.3"
quickcheck = "1"
quickcheck_macros = "1"
test-case = "1.2.3"

