[package]
name = "ecdna-evo"
version = "0.9.0"
edition = "2021"

[profile.release]
lto = "thin"
codegen-units = 1

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
csv = "1.1"
enum_dispatch = "0.3.7"
indicatif = { version = "*", features = ["rayon"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
ssa = { path = "../ssa", version = "0.2.1" }
rand = { version = "0.8.0", features = ["small_rng"] }
rand_chacha = "0.3.1"
rand_distr = "0.4.0"
rayon = "1.6"

[dev-dependencies]
fake = "2.4.3"
quickcheck = "1"
quickcheck_macros = "1"
test-case = "1.2.3"

