[workspace]
members = [
    "ecdna",
    "ecdna-data",
    "ecdna-dynamics",
    "ecdna-sim",
]

[profile.release]
lto = "thin"
codegen-units = 1

[workspace.metadata]
name = "ecdna"
version = "0.3.3"

