name: build

on:
  push:
    paths:
      - 'ecdna-plot/**'

jobs:
  build:
    name: Build python package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: build
      run: >-
        pip install -r requirements.txt
